// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both VITE_ prefixed and non-prefixed variables (for Lovable compatibility).
// .trim() removes any trailing newline (\n) or whitespace that Vercel/CI may inject
// into environment variable values. A trailing \n in the anon key corrupts the
// WebSocket URL (%0A appended) and Authorization headers, breaking real-time
// subscriptions and REST calls silently.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL || '').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY || '').trim();

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL or SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY or SUPABASE_PUBLISHABLE_KEY');

  const errorMessage = `Missing required Supabase environment variables: ${missing.join(', ')}`;

  // Don't throw in production - just log and let the app try to work
  // This allows for graceful degradation
  console.error(errorMessage);
  console.error('Current env:', {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL ? 'SET' : 'MISSING',
    SUPABASE_URL: import.meta.env.SUPABASE_URL ? 'SET' : 'MISSING',
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
    SUPABASE_PUBLISHABLE_KEY: import.meta.env.SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Single Supabase client instance for the entire app.
// Order INSERTs use a raw fetch() call (in Cart.tsx) to bypass JWT refresh hangs.
export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
    },
    global: {
      headers: {
        'X-Client-Info': 'ricos-tacos-web'
      }
    },
    db: {
      schema: 'public'
    }
  }
);

// supabaseAnon has been removed. All edge function calls during checkout now
// use raw fetch() directly, which bypasses GoTrueClient entirely and avoids
// the "Multiple GoTrueClient instances" warning. See Cart.tsx and
// SecurePaymentModal.tsx for the raw fetch() pattern.
