// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both VITE_ prefixed and non-prefixed variables (for Lovable compatibility)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL or SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY or SUPABASE_PUBLISHABLE_KEY');
  
  const errorMessage = `Missing required Supabase environment variables: ${missing.join(', ')}`;
  
  // Don't throw in production - just log and let the app try to work
  // This allows for graceful degradation
  console.error(errorMessage);
  console.error('Current env:', {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL ? 'SET' : 'MISSING',
    SUPABASE_URL: import.meta.env.SUPABASE_URL ? 'SET' : 'MISSING',
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
    SUPABASE_PUBLISHABLE_KEY: import.meta.env.SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom fetch with timeout to prevent hanging requests
const fetchWithTimeout = (timeout = 8000) => {
  return async (url: RequestInfo, init?: RequestInit) => {
    const controller = new AbortController();
    const id = setTimeout(() => controller.abort(), timeout);
    
    try {
      const response = await fetch(url, {
        ...init,
        signal: controller.signal,
      });
      clearTimeout(id);
      return response;
    } catch (error) {
      clearTimeout(id);
      if (error instanceof Error && error.name === 'AbortError') {
        console.error('Request timed out after', timeout, 'ms:', url);
        throw new Error(`Request timeout - please check your connection and try again`);
      }
      throw error;
    }
  };
};

export const supabase = createClient<Database>(
  SUPABASE_URL || '', 
  SUPABASE_PUBLISHABLE_KEY || '', 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false, // Prevent auth hanging on URL checks
    },
    global: {
      fetch: fetchWithTimeout(8000), // 8 second timeout for all requests
      headers: {
        'X-Client-Info': 'ricos-tacos-web'
      }
    },
    db: {
      schema: 'public'
    }
  }
);
